# Generated by Django 6.0.2 on 2026-04-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('styleapp', '0002_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product',)},
        ),
    ]
